# Generated by Django 2.2.6 on 2020-05-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
