# Generated by Django 2.2.6 on 2020-05-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.CharField(default='', max_length=255),
        ),
    ]
